### ISSUE TITLE
Invalid Status Message

### ISSUE THREAD

**Issue by vnp85** [melix/astro4j#519]
On trimming a ser file, the status message "trimming" stays even after everything is done.

Version: 2.11.1 dev

Steps to recreate: open "batch process", take a ser file (same with many), simple process, check the auto-trim on miscellaneous and process (custom), wait... 

Expected: status message "Finished"
Observed: statues message "Trimming" like it was still an ongoing thing

![Image](https://github.com/user-attachments/assets/ba66836e-361b-4548-9998-7e4a364bd965)

**Comment by melix** [comment]
Thanks for the bug report. I've seen several issues like this, I need to do some refactoring of the progress listeners.

**Comment by melix** [comment]
Fixed in [9dc108b](https://github.com/melix/astro4j/commit/9dc108b273d88a50275b4f27ec193438e6d6b169)

**Comment by vnp85** [comment]
Still present in 3.0.1 stable release

been like this for hours (I have been afk)

![Image](https://github.com/user-attachments/assets/d72357ee-a8c4-4cb0-9dfb-bf84ee7175e7)

**Comment by melix** [comment]
Might be something else, I don't see the batch finished message in the logs either. Possibly an error during processing... (btw 3.0.2 is out for a couple days ;))

**Comment by vnp85** [comment]
i have been on the stable branch for this once

**Comment by vnp85** [comment]
wtf 

![Image](https://github.com/user-attachments/assets/a083272d-cd2e-4f36-814a-49b3560977c0)

**Comment by melix** [comment]
Why do you have devel in the version name, that's for dev versions, not releases. https://melix.github.io/astro4j/latest/en/jsolex.html

**Comment by vnp85** [comment]
I wanted to download from here

![Image](https://github.com/user-attachments/assets/29fb873f-f19d-4cb7-9b5b-12f89f4224f5)
